# Generated by Django 3.2 on 2022-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('mini', 'Mini Unit'), ('med', 'Medium Unit'), ('lar', 'Large Unit')], max_length=5)),
                ('capacitycubicm', models.IntegerField()),
            ],
        ),
    ]
