# Generated by Django 3.2 on 2022-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='capacitycubicm',
            field=models.IntegerField(choices=[('mini', 2), ('med', 5), ('lar', 10)]),
        ),
    ]
