# Generated by Django 3.2 on 2022-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitbook', '0002_alter_unit_capacitycubicm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='capacitycubicm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Mini', 'Mini Unit'), ('Medium', 'Medium Unit'), ('Large', 'Large Unit')], max_length=6),
        ),
    ]
